#!/usr/bin/python3
"""
Generates a .tgz archive from the contents of the web_static using do_pack
"""

from fabric import Connection

servers = ['54.237.117.188', '100.25.141.192']

web_static_<year><month><day><hour><minute><second>.tgz

def do_pack():
    """
    Function that connect to the servers and archives the content
    """
    for server in servers:
        with Connection(host=server,
                        user='ubuntu',
                        connect_kwargs={
                            'key_filename':'~/.ssh/id_rsa',
                        },
                        ) as c:
                            c.local('tar cf versions/static_archive.tar web_static')

if __name__ == "__main___":
    do_pack()
